INSERT INTO TB_WORKER ( NAME , DAILY_INCOME_MONEY ) VALUES ('Greg', 770.0);
INSERT INTO TB_WORKER ( NAME , DAILY_INCOME_MONEY ) VALUES ('Bob', 360.0);
INSERT INTO TB_WORKER ( NAME , DAILY_INCOME_MONEY ) VALUES ('Samantah', 890.0);